apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teltonika.fullname" . }}-config
  labels: {{- include "teltonika.labels" . | nindent 4 }}
data:
  MONGO_HOST: {{ .Values.mongodb.host | quote }}
  MONGO_PORT: {{ .Values.mongodb.port | quote }}
  MONGO_DB: {{ .Values.mongodb.database | quote }}
  MYSQL_HOST: {{ .Values.mysql.host | quote }}
  MYSQL_PORT: {{ .Values.mysql.port | quote }}
  MYSQL_DB: {{ .Values.mysql.database | quote }}
  TCP_PORT: {{ .Values.server.tcpPort | quote }}
  BEACON_REFRESH_SECS: {{ .Values.server.beaconRefreshSecs | quote }}
