apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teltonika.secretName" . }}
  labels:
    {{- include "teltonika.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_USER: {{ include "teltonika.mongoUser" . | quote }}
  MONGO_PASS: {{ include "teltonika.mongoPass" . | quote }}
  MYSQL_USER: {{ .Values.credentials.mysqlUser | quote }}
  MYSQL_PASS: {{ .Values.credentials.mysqlPass | quote }}
