apiVersion: v1
kind: Service
metadata:
  name: {{ include "teltonika.fullname" . }}-server
  labels:
    {{- include "teltonika.labels" . | nindent 4 }}
    {{- include "teltonika.server.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  {{- if .Values.server.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.server.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "teltonika.server.selectorLabels" . | nindent 4 }}
  ports:
    - name: teltonika-tcp
      protocol: TCP
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.tcpPort }}
